import polars as pl
import numpy as np

def generate_macro_features(lf: pl.LazyFrame) -> pl.LazyFrame:
    """
    Generates macro features out-of-core using pure Polars expressions.
    Expects a LazyFrame with columns: 'Date', 'NIFTY_Close', 'VIX_Close'.

    Calculations:
      - VIX 5-day and 10-day Simple Moving Averages
      - VIX 14-day RSI
      - VIX Rate of Change (ROC) over 3 days
      - NIFTY 50 Rate of Change (ROC) over 3 days

    Returns a pl.LazyFrame with the appended feature columns.
    """
    # Enforce strict chronological order to ensure rolling calculations are correct.
    lf = lf.sort("Date")

    # Pre-calculate differences for RSI
    lf = lf.with_columns([
        (pl.col("VIX_Close") - pl.col("VIX_Close").shift(1)).alias("vix_diff")
    ])

    # Calculate gains and losses for RSI
    lf = lf.with_columns([
        pl.when(pl.col("vix_diff") > 0).then(pl.col("vix_diff")).otherwise(0).alias("vix_gain"),
        pl.when(pl.col("vix_diff") < 0).then(pl.col("vix_diff").abs()).otherwise(0).alias("vix_loss")
    ])

    # Calculate RSI using Wilder's Smoothing (alpha = 1/14)
    # Note: Using exponential moving average to approximate Wilder's Moving Average
    period = 14
    alpha = 1.0 / period

    lf = lf.with_columns([
        pl.col("vix_gain").ewm_mean(alpha=alpha, adjust=False).alias("vix_avg_gain"),
        pl.col("vix_loss").ewm_mean(alpha=alpha, adjust=False).alias("vix_avg_loss")
    ])

    lf = lf.with_columns([
        (100.0 - (100.0 / (1.0 + (pl.col("vix_avg_gain") / pl.col("vix_avg_loss"))))).alias("VIX_RSI_14")
    ])

    # Calculate SMAs and ROCs
    lf = lf.with_columns([
        # VIX 5-day SMA
        pl.col("VIX_Close").rolling_mean(window_size=5).alias("VIX_SMA_5"),

        # VIX 10-day SMA
        pl.col("VIX_Close").rolling_mean(window_size=10).alias("VIX_SMA_10"),

        # VIX 3-day ROC: ((Price - Price_n_periods_ago) / Price_n_periods_ago) * 100
        ((pl.col("VIX_Close") - pl.col("VIX_Close").shift(3)) / pl.col("VIX_Close").shift(3) * 100.0).alias("VIX_ROC_3"),

        # NIFTY 3-day ROC
        ((pl.col("NIFTY_Close") - pl.col("NIFTY_Close").shift(3)) / pl.col("NIFTY_Close").shift(3) * 100.0).alias("NIFTY_ROC_3")
    ])

    # Drop intermediate columns used for RSI calculation
    lf = lf.drop(["vix_diff", "vix_gain", "vix_loss", "vix_avg_gain", "vix_avg_loss"])

    return lf

def label_vix_regimes(lf: pl.LazyFrame, lookforward_days: int = 3, spike_threshold: float = 0.15) -> pl.LazyFrame:
    """
    Applies forward-looking labeling logic to predict severe volatility spikes.

    Logic:
      - For every row, look ahead `lookforward_days`.
      - Find the maximum VIX_Close in that forward window.
      - If Max_Forward_VIX >= VIX_Close * (1 + spike_threshold), Target = 1 (Spike predicted), Else 0.

    Also applies a strict `.drop_nulls()` at the end to ensure clean data for ML.
    """
    # Ensure sorted order just in case
    lf = lf.sort("Date")

    # We want to look strictly *forward* by lookforward_days.
    # To do this natively in Polars with a rolling window, we can reverse the dataframe,
    # do a rolling max, and then reverse it back.
    # Alternatively, we can use the `shift` function to build a forward max.

    # For small, fixed lookforward_days like 3, explicit shifting is very fast and pure:
    forward_cols = [pl.col("VIX_Close").shift(-i) for i in range(1, lookforward_days + 1)]

    lf = lf.with_columns([
        pl.max_horizontal(forward_cols).alias("Max_Forward_VIX")
    ])

    # Label generation
    lf = lf.with_columns([
        pl.when(pl.col("Max_Forward_VIX") >= (pl.col("VIX_Close") * (1.0 + spike_threshold)))
          .then(1)
          .otherwise(0)
          .alias("Target")
    ])

    # Drop the intermediate forward looking column

    lf = lf.drop_nulls()
    lf = lf.drop("Max_Forward_VIX")

    # Drop all nulls generated by rolling indicators and forward shifts to provide perfectly clean ML data


    return lf

def balance_classes(lf: pl.LazyFrame, random_state: int = 42) -> pl.LazyFrame:
    """
    Performs strict 2:1 undersampling (Zeros to Ones) to balance the heavily skewed dataset.
    Volatility spikes are rare, so we sample the 0s to be exactly twice the number of 1s.

    Because global undersampling requires knowing the exact counts of each class,
    we materialise (collect) briefly to perform the exact sampling, then return a LazyFrame.
    """
    # Set seed for reproducibility in sampling
    np.random.seed(random_state)

    # Eager evaluation is required here to securely count and sample the entire dataset globally
    df = lf.collect()

    # Separate the classes
    df_ones = df.filter(pl.col("Target") == 1)
    df_zeros = df.filter(pl.col("Target") == 0)

    n_ones = df_ones.height
    n_zeros_target = n_ones * 2

    # If we somehow have fewer zeros than twice the ones, just take all zeros (edge case fallback)
    if n_zeros_target > df_zeros.height:
        n_zeros_target = df_zeros.height

    if n_zeros_target > 0:
        # Sample the zeros to match the 2:1 ratio
        df_zeros_sampled = df_zeros.sample(n=n_zeros_target, seed=random_state)
    else:
        df_zeros_sampled = df_zeros

    # Recombine and sort chronologically again
    df_balanced = pl.concat([df_ones, df_zeros_sampled]).sort("Date")

    # Return as a LazyFrame to resume out-of-core compatibility in the pipeline
    return df_balanced.lazy()
